// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCNQNdGGhbLPE6GoONg0LJCvUrkqU-BNjk',
    appId: '1:375302401533:web:86e49ebdf08e7f0ac03d94',
    messagingSenderId: '375302401533',
    projectId: 'roamly-aba1d',
    authDomain: 'roamly-aba1d.firebaseapp.com',
    storageBucket: 'roamly-aba1d.firebasestorage.app',
    measurementId: 'G-T74WR8X4CK',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCfYjF0coKLjuUyHlibIYyiDPk4qCAlxDo',
    appId: '1:375302401533:android:18e2ee55f60cd0ebc03d94',
    messagingSenderId: '375302401533',
    projectId: 'roamly-aba1d',
    storageBucket: 'roamly-aba1d.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDaWj1Ohqcd2q5_yeWljVcUf3PJFGNeeAE',
    appId: '1:375302401533:ios:338d463eff2c6217c03d94',
    messagingSenderId: '375302401533',
    projectId: 'roamly-aba1d',
    storageBucket: 'roamly-aba1d.firebasestorage.app',
    iosBundleId: 'com.example.ufmtask',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDaWj1Ohqcd2q5_yeWljVcUf3PJFGNeeAE',
    appId: '1:375302401533:ios:338d463eff2c6217c03d94',
    messagingSenderId: '375302401533',
    projectId: 'roamly-aba1d',
    storageBucket: 'roamly-aba1d.firebasestorage.app',
    iosBundleId: 'com.example.ufmtask',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCNQNdGGhbLPE6GoONg0LJCvUrkqU-BNjk',
    appId: '1:375302401533:web:72e9e274b48246a2c03d94',
    messagingSenderId: '375302401533',
    projectId: 'roamly-aba1d',
    authDomain: 'roamly-aba1d.firebaseapp.com',
    storageBucket: 'roamly-aba1d.firebasestorage.app',
    measurementId: 'G-CFKYB19TSV',
  );
}
